name = "coffee"
description = ""
# An optional tags to allow quick search
tags = ["dark", "simple", "mermaid", "katex"]
license = "MIT"
homepage = "https://github.com/Myxogastria0808/coffee"
# The minimum version of Zola required
min_version = "0.19.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra.coffee]
# default value: 'en'
lang = "en"
# default value: 'coffee theme'
title = "coffee theme"
# default value: 'This blog is made by zola.'
description = "This blog is made by zola."
# default value: 'blog'
keyword = "blog"
# default value: 'https://raw.githubusercontent.com/Myxogastria0808/coffee/refs/heads/main/static/favicon.ico'
shortcut_icon = "https://raw.githubusercontent.com/Myxogastria0808/coffee/refs/heads/main/static/favicon.ico"
# default value: ''
twitter_site = ""
# default value: '@yuki_osada0808'
twitter_creator = "@yuki_osada0808"
# default value: 'https://raw.githubusercontent.com/Myxogastria0808/coffee/refs/heads/main/static/coffee.webp'
about_image = "https://raw.githubusercontent.com/Myxogastria0808/coffee/refs/heads/main/static/coffee.webp"
# default value: 'coffee theme'
about_image_alt = "coffee theme"
# default value: 'https://raw.githubusercontent.com/Myxogastria0808/coffee/refs/heads/main/static/coffee.webp'
image = "https://raw.githubusercontent.com/Myxogastria0808/coffee/refs/heads/main/static/coffee.webp"
# default value: 'coffee theme'
image_alt = "coffee theme"
# default value: '512'
image_width = "512"
# default value: '512'
image_height = "512"

# The theme author info: you!
[author]
name = "Yuki Osada (Myxogastria0808)"
homepage = "https://yukiosada.work"
